{
 "title": "Sensors",
 "tags": [ "Sensors" ],
 "time": { "from": "2025-06-20T16:04:08.104Z", "to": "2025-06-20T16:05:01.475Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Machine001", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor001",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"max\",\r\n                       \"maxQA\": {\"$max\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    },
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"min\",\r\n                       \"minQA\": {\"$min\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    },
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"avg\",\r\n                       \"avgQA\": {\"$avg\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Sensor001",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Sensor002",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 8 },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"max\",\r\n                       \"maxQA\": {\"$max\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    },
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"min\",\r\n                       \"minQA\": {\"$min\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    },
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"avg\",\r\n                       \"avgQA\": {\"$avg\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Sensor002",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Sensor003",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor003\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 15 },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor003\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"max\",\r\n                       \"maxQA\": {\"$max\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    },
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor003\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"min\",\r\n                       \"minQA\": {\"$min\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    },
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor003\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    },\r\n    {\r\n        \"$group\":\r\n                    {\r\n                       \"_id\": \"avg\",\r\n                       \"avgQA\": {\"$avg\": \"$sensorValue\"} \r\n                    }\r\n                    \r\n    \r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Sensor003",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "sensors",
     "queryLanguage": "json",
     "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor003\",\r\n        \"machineName\": \"Machine001\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
    }
   ]
  },
  {
   "title": "Machine002",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensor001",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 23 },
     "targets": [
      {
       "collection": "sensors",
       "queryLanguage": "json",
       "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine002\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
      }
     ]
    },
    {
     "title": "Sensor001",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "collection": "sensors",
       "queryLanguage": "json",
       "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor001\",\r\n        \"machineName\": \"Machine002\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
      }
     ]
    },
    {
     "title": "Sensor002",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 29 },
     "targets": [
      {
       "collection": "sensors",
       "queryLanguage": "json",
       "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine002\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
      }
     ]
    },
    {
     "title": "Sensor002",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "collection": "sensors",
       "queryLanguage": "json",
       "queryText": "\r\n[\r\n    {\r\n        \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                            }\r\n                        },\r\n                \"$lt\": {\r\n                    \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                            }\r\n                        }\r\n                    },\r\n\t\t\"sensorName\": \"Sensor002\",\r\n        \"machineName\": \"Machine002\",\r\n        \"lineName\": \"Line001\"  \r\n                  }\r\n\t\t\r\n    }\r\n]\r\n"
      }
     ]
    }
   ]
  }
 ]
}